apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: murl
  name: murl-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: murl
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: murl
    spec:
      containers:
      - image: 679101398422.dkr.ecr.us-east-2.amazonaws.com/khg-dev
        imagePullPolicy: Always
        name: murl
        ports:
        - containerPort: 9100
          protocol: TCP