resource_types:
  - name: k8s
    type: docker-image
    source:
      repository: zlabjp/kubernetes-resource
      tag: "1.17"

resources:
  - name: src
    type: git
    source:
      uri: ((git-url))
      branch: ((git-branch))
  - name: release-bucket
    type: s3
    source:
      bucket: ((s3-bucket))
      versioned_file: releases/murl
      region_name: ((s3-region))
      access_key_id: ((s3-access-key-id))
      secret_access_key: ((s3-secret-access-key))
  - name: murl-image
    type: docker-image
    source:
      repository: ((ecr-registry-url))
      aws_access_key_id: ((ecr-aki))
      aws_secret_access_key: ((ecr-sak))
      aws_region: ((ecr-region))
  - name: khg-k8s
    type: k8s
    source:
      server: ((k8s-api-server-url))
      namespace: ((k8s-namespace))
      certificate_authority: ((k8s-cad))
      kubeconfig: ((k8s-kube-conf)))
jobs:
  - name: build-test-and-push-to-s3
    public: true
    plan:
      - get: src
        trigger: true
      - task: build-and-test
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: golang
          inputs:
            - name: src
              path: source
          outputs:
            - name: release
              path: output
          run:
            path: sh
            args:
              - -exc
              - |
                export GOPATH="/source"
                cd source
                go get -d -t -v ./...
                go build -o ../output/release
                go test
      - put: release-bucket
        params:
          file: release/murl

  - name: build-oci-image
    plan:
       - get: release-bucket
         trigger: true
       - get: src
       - task: create-oci-image
         privileged: true
         config:
           platform: linux
           image_resource:
             type: registry-image
             source:
               repository: vito/oci-build-task
           inputs:
             - name: src
             - name: release-bucket
               path: bin
           outputs:
             - name: image
           params:
             DOCKERFILE: src/ci/Dockerfile
           run:
             path: build
       - put: murl-image
         params:
           import_file: image/image.tar

  - name: pull-and-deploy
    plan:
      - get: src
      - get: murl-image
        trigger: true
      - put: khg-k8s
        params:
          kubectl: apply -f src/k8s